export const userConstants = {
  USER_LOADING: "USER_LOADING",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILURE: "AUTH_FAILURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  UPDATE_USER: "UPDATE_USER"
};

export const bookmarksConstants = {
  GET_BOOKMARKS: "GET_BOOKMARKS",
  ADD_BOOKMARK: "ADD_BOOKMARK",
  DELETE_BOOKMARK: "DELETE_BOOKMARK",
  UPDATE_BOOKMARK: "UPDATE_BOOKMARK",
  ADD_TAG_TO_BOOKMARK: "ADD_TAG_TO_BOOKMARK",
  DELETE_TAG_FROM_BOOKMARK: "DELETE_TAG_FROM_BOOKMARK",
  BOOKMARKS_LOADING: "BOOKMARKS_LOADING",
};

export const tagsConstants = {
  GET_TAGS: "GET_TAGS",
  ADD_TAG: "ADD_TAG",
  DELETE_TAG: "DELETE_TAG",
  UPDATE_TAG: "UPDATE_TAG",
  TAGS_LOADING: "TAGS_LOADING",
};

export const collectionsConstants = {
  GET_COLLECTIONS: "GET_COLLECTIONS",
  ADD_COLLECTION: "ADD_COLLECTION",
  DELETE_COLLECTION: "DELETE_COLLECTION",
  UPDATE_COLLECTION: "UPDATE_COLLECTION",
  COLLECTIONS_LOADING: "COLLECTIONS_LOADING",
};

export const errorsConstants = {
  SET_ERRORS: "SET_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
};
